package.json
=> [figma]:update to 0.3.0

package.json
=> [figma]:update to 0.3.1

package.json
=> [figma]:update to 0.3.2

package.json
feat: set icon default size = 16
=> [figma]:update to 0.3.3

package.json
=> [figma]:update to 0.3.4

package.json
=> [figma]:update to 0.3.5

package.json
feat: fix icon-currencylayer-cl
=> [figma]:update to 1.0.19

package.json
=> [figma]:update to 1.0.24

package.json
=> [figma]:update to 1.0.27

package.json
=> [figma]:update to 1.0.29

package.json
=> [figma]:update to 1.0.38

package.json
feat: tweak sort-rise & sort-drop
=> [figma]:update to 1.1.42

package.json
=> [figma]:update to 1.1.43

package.json
=> [figma]:update to 1.1.53

package.json
=> [figma]:update to 1.1.56

package.json
=> [figma]:update to 1.1.66

package.json
=> [figma]:update to 1.1.67

package.json
=> [figma]:update to 1.1.68

package.json
=> [figma]:update to 1.1.69

package.json
=> [figma]:update to 1.1.73

package.json
=> [figma]:update to 1.1.75

package.json
=> [figma]:update to 1.1.77

package.json
=> [figma]:update to 1.1.78

package.json
=> [figma]:update to 1.1.81

package.json
=> [figma]:update to 1.1.82

package.json
=> [figma]:update to 1.1.90

package.json
=> [figma]:update to 1.1.91

package.json
=> [figma]:update to 1.2.4

package.json
feat: fix extra space in "pinch" icon
=> [figma]:update to 1.3.10

package.json
feat: temporary remove mix-blend-mode for 2 problematic icons
=> [figma]:update to 1.3.11

package.json
=> [figma]:update to 1.3.12

package.json
=> [figma]:update to 1.3.13

package.json
=> [figma]:update to 1.3.15

package.json
fix avatar-group-cl icon ,fix avatar-project-cl icon
=> [figma]:update to 1.3.16

package.json
feat: add logo for futu and leyuansu
=> [figma]:update to 1.3.17

package.json
=> [figma]:update to 1.3.19

package.json
=> [figma]:update to 1.3.20

package.json
=> [figma]:update to 1.3.21

package.json
=> [figma]:update to 1.3.22

package.json
=> [figma]:update to 1.3.24

package.json
=> [figma]:update to 1.3.25

package.json
feat: add branch, thumb-up and 4 flags
=> [figma]:update to 1.3.26

package.json
=> [figma]:update to 1.3.27

package.json
feat: add icon "add-to-page" by cece
=> [figma]:update to 1.3.28

package.json
feat: fix operator-include direction issue
=> [figma]:update to 1.3.29

package.json
=> [figma]:update to 1.3.30

package.json
=> [figma]:update to 1.3.31

package.json
=> [figma]:update to 1.3.32

package.json
=> [figma]:update to 1.3.33

package.json
=> [figma]:update to 1.3.34

package.json
=> [figma]:update to 1.3.35

package.json
=> [figma]:update to 1.3.36

package.json
=> Revert "[figma]:update to 1.4.6"

package.json
=> [figma]:update to 1.5.10

package.json
fix: delete "approve-cancelled"
=> [figma]:update to 1.5.11

package.json
=> [figma]:update to 1.5.12

package.json
=> [figma]:update to 1.5.13

package.json
feat: refresh all nav icons for dark mode compatability
=> [figma]:update to 1.5.14

package.json
feat: add logo-jiguang-cl; add logo-fcm-cl;
=> [figma]:update to 1.5.15

package.json
=> [figma]:update to 1.5.16

package.json
feat: add test-split & test-race
=> [figma]:update to 1.5.17

package.json
=> [figma]:update to 1.5.18

package.json
=> [figma]:update to 1.5.19

package.json
=> [figma]:update to 1.5.21

package.json
=> [figma]:update to 1.5.28

package.json
feat: add pin, pin-unsave, unsave
=> [figma]:update to 1.6.0

package.json
=> [figma]:update to 1.17.8

package.json
=> [figma]:update to 1.17.9

package.json
=> [figma]:update to 1.17.10

package.json
=> [figma]:update to 1.17.11

package.json
add arrow-go-back、arrow-go-forward
=> [figma]:update to 1.17.12

package.json
=> [figma]:update to 1.17.13

package.json
=> [figma]:update to 1.17.14

package.json
=> [figma]:update to 1.17.16

package.json
=> [figma]:update to 1.17.17

package.json
=> [figma]:update to 1.17.18

package.json
=> [figma]:update to 1.17.21

package.json
=> [figma]:update to 1.18.1

package.json
=> [figma]:update to 1.18.2

package.json
=> [figma]:update to 1.18.4

package.json
=> [figma]:update to 1.18.5

package.json
=> [figma]:update to 1.18.6

package.json
=> [figma]:update to 1.18.7

package.json
=> [figma]:update to 1.18.8

package.json
=> [figma]:update to 1.18.10

package.json
feat: add table-col, table-row
=> [figma]:update to 1.18.12

package.json
feat: add copy-query, copy-ddl
=> [figma]:update to 1.18.13

package.json
feat: add logo-trino, logo-starrocks
=> [figma]:update to 1.18.14

package.json
=> [figma]:update to 1.18.15

package.json
feat: add auto layout & fix logo suffix
=> [figma]:update to 1.18.16

package.json
feat: add offline-sync, debug-play, satelite-dish
=> [figma]:update to 1.18.17

package.json
feat: add text-case, text-whole-match
=> [figma]:update to 1.18.18

package.json
=> [figma]:update to 1.18.19

package.json
=> [figma]:update to 1.18.20

package.json
=> [figma]:update to 1.18.21

package.json
=> [figma]:update to 1.18.22

package.json
=> [figma]:update to 1.18.11

package.json
=> [figma]:update to 1.18.24

package.json
=> [figma]:update to 1.18.25

package.json
=> [figma]:update to 1.18.26

package.json
=> [figma]:update to 1.18.27

package.json
新增 property-certified、property-uncertified、add-index三个icon
=> [figma]:update to 1.18.29

package.json
新增 property-certified、property-uncertified、add-index
=> [figma]:update to 1.18.30

package.json
=> [figma]:update to 1.18.31

package.json
=> [figma]:update to 1.18.32

package.json
=> [figma]:update to 1.18.33

package.json
=> [figma]:update to 1.18.34

package.json
=> [figma]:update to 1.18.36

package.json
=> [figma]:update to 1.18.37

package.json
=> [figma]:update to 1.18.38

package.json
=> [figma]:update to 1.18.39

package.json
=> [figma]:update to 1.18.40

package.json
add Report-Reading-cl、Copywriting-AI-cl icon
=> [figma]:update to 1.20.1

package.json
新增  align-legend-top、align-legend-bottom、align-legend-left、align-legend-right 四个 icon
=> [figma]:update to 1.20.2

package.json
=> [figma]:update to 1.20.3

package.json
=> [figma]:update to 1.20.8

package.json
=> [figma]:update to 1.20.9

package.json
=> [figma]:update to 1.20.12

package.json
=> [figma]:update to 1.20.13

package.json
=> [figma]:update to 1.20.15

package.json
fix: remove empty-state components
=> [figma]:update to 1.20.16

package.json
=> [figma]:update to 1.20.17

package.json
=> [figma]:update to 1.20.20

package.json
=> [figma]:update to 1.20.24

package.json
fix: try add dashboard-generate
=> [figma]:update to 1.20.26

package.json
=> [figma]:update to 1.20.27

package.json
=> [figma]:update to 1.20.30

package.json
=> [figma]:update to 1.20.35

package.json
=> [figma]:update to 1.20.36
